### ISSUE TITLE
error on `Import yaml`

### ISSUE THREAD

**Issue by djdesign** [Bemmu/PyNamecheap#10]
Checking out your script
keep running into error on `Import yaml`

Any help would be appreciated?
```
Traceback (most recent call last):
  File "./namecheap-api-cli", line 6, in <module>
    import yaml
ImportError: No module named ‘yaml’
```

**Local Enviroment**:
macOS 10.12.2

Python 3.5.2
pyyaml-3.12
libyaml-0.1.7

**Comment by agrrh** [comment]
@djdesign 
I assume that one of the following things happened: either you have pyyaml installed as python 2.x module or default python executable points to version 2.x.

Could you please check it by executing following commands and posting here a result:

```
# To check which version is default one
/usr/bin/env python -V

# To check if module available at default path
find /usr/local/lib/python*/site-packages -type d -maxdepth 1 -iname *yaml*
```

**Comment by djdesign** [comment]
Hey @agrrh,

After doing some digging that would explain it. 
That my “assumption” led me to be installing those base packages they were not being installed into the correct library.
Checking showed I needed to use `pip3.5` todo my install, figured out I was installing to the wrong python version. Thanks again!

```
#checking version
~/$ /usr/bin/env python -V
Python 3.5.2

#checking path
~/$ ls -la $(which python)
/usr/local/bin/python -> /usr/local/bin/python3.5

#checking if module exists
~/$ find /usr/local/lib/python*/site-packages -type d -maxdepth 1 -iname *yaml*
nothing found for wildcard “*yaml*”

# resolution install to correct pip version (my mistake)
~/$ pip3.5 install requests pyyaml
```

**Comment by Bemmu** [comment]
Why do we import yaml anyway, doesn't seem to be used?
