### ISSUE TITLE
How to use domains_getList ?

### ISSUE THREAD

**Issue by firaxis** [Bemmu/PyNamecheap#7]
Hi!

Thanks for great job!

I'm trying to use your code to get domains list at my namecheap account, but it seems that I'm using it wrong.

Here's how I'm trying to get domains list:

```
import sys
import os
import yaml
from namecheap import Api, ApiError
from credentials import api_key, username, ip_address
api = Api(username, api_key, username, ip_address)
domains=api.domains_getList
list(domains)
```

But I'm getting following error:
`
TypeError: 'method' object is not iterable
`

Could you please suggest how to use this method ?

Thanks!

**Comment by agrrh** [comment]
It's as simple as that:

```
api.domains_getList()
```

**Comment by firaxis** [comment]
@agrrh Many thanks!
